name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Gradle
      run: ./gradlew build --info
       # Manual upload of coverage report, see https://github.com/kt3k/coveralls-gradle-plugin/issues/85
    - name: Upload code coverage to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          ./gradlew codeCoverageReport coveralls
          curl -F 'json_file=@build/report.json' 'https://coveralls.io/api/v1/jobs'
    - name: Deploy to Github Package Registry
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gradle publish